apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
spec:
  selector:
    app: spark-master
  ports:
    - name: spark-master-port
      port: 7077
      targetPort: 7077
    - name: spark-ui-port
      port: 8080
      targetPort: 8080
  type: ClusterIP
