apiVersion: v1
kind: Pod
metadata:
  name: spark-master
  labels:
    app: spark
spec:
  containers:
  - name: spark-master
    image: bitnami/spark:latest
    ports:
    - containerPort: 7077
    - containerPort: 8080
