apiVersion: v1
kind: Pod
metadata:
  name: spark-worker
  labels:
    app: spark
spec:
  containers:
  - name: spark-worker
    image: bitnami/spark:latest
    ports:
    - containerPort: 8081
    env:
    - name: SPARK_MODE
      value: "worker"
    - name: SPARK_MASTER_URL
      value: "spark://spark-master:7077"
